project:
  type: website
  output-dir: docs

website:
  title: Pinki Kumari
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: ta.qmd
        text: Teaching Assistant
      - href: projects.qmd
        text: Projects
      - href: files/Resume_PinkiKumari.pdf
        text: Resume
        

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    highlight-style: a11y-dark
    code-copy: true
    code-overflow: wrap

execute: 
  freeze: auto
